### ISSUE TITLE
Wrong rendered text

### ISSUE THREAD

**Issue by hirose31** [moznion/Pod-Text-Color-Delight#2]
I found rendered text with Pod::Text::Color::Deight is wrong.
For example, there are differences of functions list in DESCRIPTION section.
Do you have any idea to fix this problem?
- `perldoc Time::HiRes`

```
...
     The following functions can be imported from this module.  No functions
     are exported by default.

     gettimeofday ()
         In array context returns a two-element array with the seconds and
...
     usleep ( $useconds )
...
     nanosleep ( $nanoseconds )
...
```
- `perldoc -MPod::Text::Color::Delight Time::HiRes`

```
...
    The following functions can be imported from this module. No functions
    are exported by default.

    "nanosleep"
        In array context returns a two-element array with the seconds and
...
    "Time::HiRes::time()"
...
    "Time::HiRes::clock_nanosleep()"
...
```

**Comment by moznion** [comment]
Thank you for your reporting.

Yes, I found the same bug yesterday, I'm fixing now.
Please just a moment...

**Comment by moznion** [comment]
AnyEvent::WebService::ImKayacでも同じようなこと起こってるから、なんか関係あると思う > @moznion

**Comment by moznion** [comment]
Okay, I fixed!!
